# Generated by Django 5.2.4 on 2025-11-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='current_user',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
